version: "3.8"

services:
  ballot.app:
    build:
      context: .
    entrypoint: /app/scripts/init.ballot.sh
    volumes:

      - type: bind
        source: ./ballot
        target: /app/ballot/

      - type: volume
        source: ballot-data
        target: /data

    ports:
      - "8080:80"  # Main port
      - "5555:5555"  # Debug port
    networks:
      - ballot-ntw

volumes:
  ballot-data:

networks:
  # The presence of these objects is sufficient to define them
  ballot-ntw: {}
