# Generated by Django 4.2.13 on 2024-05-13 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('A', 'Afirmative'), ('B', 'Blank'), ('N', 'Null')], default='N', max_length=1)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voting.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voting.politicalparty')),
            ],
        ),
        migrations.CreateModel(
            name='Restult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vote_type', models.CharField(choices=[('A', 'Afirmative'), ('B', 'Blank'), ('N', 'Null')], default='N', max_length=1)),
                ('votes', models.IntegerField()),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='voting.politicalparty')),
            ],
        ),
    ]
