# Generated by Django 4.2.13 on 2024-05-13 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_vote_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='restult',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='voting.election'),
        ),
    ]
